version: "3.7"
services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfiles/Dockerfile
    command: ["npm", "run", "dev", "--", "--host"]
    ports:
      - "5173:5173"
    volumes:
      - "./app:/usr/src/app"
    restart: "no"